# Generated by Django 5.1.1 on 2025-09-19 18:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=255, null=True)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("storage_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "kwh_estimate",
                    models.FloatField(
                        help_text="Estimated kWh energy consumption",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "co2_g_estimate",
                    models.FloatField(
                        help_text="Estimated CO2 emissions in grams",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "impact_score",
                    models.IntegerField(
                        help_text="Impact score from 0-100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="files.fileasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "files_fileasset",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("duplicate", "Reuse Existing File"),
                            ("compress", "Compress File"),
                            ("share_link", "Share Link Instead"),
                            ("archive", "Archive Old File"),
                            ("optimize", "Optimize File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="files.fileasset",
                    ),
                ),
            ],
            options={
                "db_table": "files_recommendation",
            },
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(fields=["sha256"], name="files_filea_sha256_68bd48_idx"),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["user", "-created_at"], name="files_filea_user_id_ec9104_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["created_at"], name="files_filea_created_600b56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["file", "-created_at"], name="files_recom_file_id_d3b271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["kind"], name="files_recom_kind_81d856_idx"),
        ),
    ]
